name: ui
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  dropdown_button2: ^2.3.9
  file_picker: ^5.5.0
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  get: ^4.6.5
  http: ^1.1.0
  image_picker: ^0.8.4+2
  uuid: ^4.0.0
  animated_text_kit: ^4.2.2
  footer: ^0.0.4
  web_smooth_scroll: ^1.1.0
  carousel_slider: ^4.2.1
  dots_indicator: ^3.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: logo
      fonts:
        - asset: assets/fonts/JosefinSlab-Italic-VariableFont_wght.ttf